auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: mutefrank
url: http://mutefrank.github.io/
feed: /atom.xml
author_info: <a href="http://mutefrank.github.io/">mutefrank/a>
